import { RowDataPacket } from "mysql2";

export interface BannedRecord {
    range:     string;
    score:     number;
    country:   string | null;
    userAgent: string | null;
    reason:    string;
    comment: 'Automatically generated by @riavzon/botDetector';
}

export interface HighRiskRecord {
    range: string;
    visitorId: string;
    score: number;
    country: string | null;
    region: string | null;
    regionName: string | null;
    city: string | null;
    lat: string | null;
    lon: string | null;
    timezone: string | null;
    isp: string | null;
    org: string | null;
    browser: string | null;
    browserType: string | null;
    browserVersion: string | null;
    os: string | null;
    deviceType: string | null;
    deviceVendor: string | null;
    deviceModel: string | null;
    proxy: boolean;
    hosting: boolean;
    requestCount: number;
    firstSeen: string | null;
    lastSeen: string | null;
    comment: 'Automatically generated by @riavzon/botDetector';
}


export interface BannedRow extends RowDataPacket {
    ip_address: string;
    country:    string | null;
    user_agent: string | null;
    reason:     string;
    score:      number;
}

export interface HighRiskRow extends RowDataPacket {
    ip_address:                string;
    visitor_id:                string;
    suspicious_activity_score: number;
    country: string | null;
    region: string | null;
    region_name: string | null;
    city: string | null;
    lat: string | null;
    lon: string | null;
    timezone: string | null;
    isp: string | null;
    org: string | null;
    browser: string | null;
    browserType: string | null;
    browserVersion: string | null;
    os: string | null;
    device_type: string | null;
    deviceVendor: string | null;
    deviceModel: string | null;
    proxy: boolean;
    hosting: boolean;
    request_count: number;
    first_seen: Date | null;
    last_seen: Date | null;
}