import { compiler } from '@riavzon/shield-base';
import { getPool } from '../config/dbConnection.js';
import { getConfiguration } from '../config/config.js';
import { getLogger } from '../utils/logger.js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { BannedRecord, BannedRow, HighRiskRecord, HighRiskRow } from '../types/generator.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const MMDB_DIR = path.resolve(__dirname, 'mmdb');


async function buildBannedMmdb(generateTypes: boolean, mmdbctlPath: string): Promise<void> {
    const log = getLogger().child({ service: 'BOT DETECTOR', branch: 'generator', db: 'banned' });

    const [rows] = await getPool().execute<BannedRow[]>(
        `SELECT ip_address, country, user_agent, reason, score
         FROM banned
         WHERE ip_address IS NOT NULL`
    );

    if (rows.length === 0) {
        log.info('No banned IPs — skipping banned.mmdb');
        return;
    }

    const data: BannedRecord[] = rows.map(r => ({
        range: r.ip_address,
        score: r.score,
        country: r.country,
        userAgent: r.user_agent,
        reason: r.reason,
        comment: 'Automatically generated by @riavzon/botDetector',
    }));

    await compiler<BannedRecord>({ data, dataBaseName: 'banned', outputPath: MMDB_DIR, mmdbPath: mmdbctlPath, generateTypes });
    log.info(`banned.mmdb compiled — ${data.length} entries`);

    if (getConfiguration().generator.deleteAfterBuild) {
        const compiled = rows.map(r => r.ip_address);
        await getPool().execute(
            `DELETE FROM banned WHERE ip_address IN (${compiled.map(() => '?').join(',')})`,
            compiled
        );
        log.info(`Deleted ${compiled.length} rows from banned after build`);
    }
}


async function buildHighRiskMmdb(scoreThreshold: number, generateTypes: boolean, mmdbctlPath: string): Promise<void> {
    const log = getLogger().child({ service: 'BOT DETECTOR', branch: 'generator', db: 'highRisk' });
    const [rows] = await getPool().execute<HighRiskRow[]>(
        `SELECT
           ip_address, visitor_id, suspicious_activity_score,
           country, region, region_name, city, lat, lon, timezone,
           isp, org, browser, browserType, browserVersion, os,
           device_type, deviceVendor, deviceModel,
           proxy, hosting, request_count, first_seen, last_seen
         FROM visitors
         WHERE suspicious_activity_score >= ? AND ip_address IS NOT NULL`,
        [scoreThreshold]
    );

    if (rows.length === 0) {
        log.info(`No high-risk visitors (score >= ${scoreThreshold}) — skipping highRisk.mmdb`);
        return;
    }

    const data: HighRiskRecord[] = rows.map(r => ({
        range: r.ip_address,
        visitorId: r.visitor_id,
        score: r.suspicious_activity_score,
        country: r.country,
        region: r.region,
        regionName: r.region_name,
        city: r.city,
        lat: r.lat,
        lon: r.lon,
        timezone: r.timezone,
        isp: r.isp,
        org: r.org,
        browser: r.browser,
        browserType: r.browserType,
        browserVersion: r.browserVersion,
        os: r.os,
        deviceType: r.device_type,
        deviceVendor: r.deviceVendor,
        deviceModel: r.deviceModel,
        proxy: Boolean(r.proxy),
        hosting: Boolean(r.hosting),
        requestCount: r.request_count,
        firstSeen: r.first_seen ? r.first_seen.toISOString() : null,
        lastSeen: r.last_seen  ? r.last_seen.toISOString()  : null,
        comment: 'Automatically generated by @riavzon/botDetector',
    }));

    await compiler<HighRiskRecord>({ data, dataBaseName: 'highRisk', outputPath: MMDB_DIR, mmdbPath: mmdbctlPath, generateTypes });
    log.info(`highRisk.mmdb compiled — ${data.length} entries`);

    if (getConfiguration().generator.deleteAfterBuild) {
        const compiled = rows.map(r => r.ip_address);
        await getPool().execute(
            `DELETE FROM visitors WHERE ip_address IN (${compiled.map(() => '?').join(',')}) AND suspicious_activity_score >= ?`,
            [...compiled, scoreThreshold]
        );
        log.info(`Deleted ${compiled.length} rows from visitors after build`);
    }
}


async function runCycle(): Promise<void> {
    const log = getLogger().child({ service: 'BOT DETECTOR', branch: 'generator' });
    const { generator } = getConfiguration();

    log.info('MMDB generation cycle started');
    try {
        await Promise.all([
            buildBannedMmdb(generator.generateTypes, generator.mmdbctlPath),
            buildHighRiskMmdb(generator.scoreThreshold, generator.generateTypes, generator.mmdbctlPath),
        ]);
        log.info('MMDB generation cycle complete');
    } catch (err) {
        log.error({ err }, 'MMDB generation cycle failed');
    }
}


export async function runGeneration(): Promise<void> {
    return runCycle();
}