import { compiler } from '@riavzon/shield-base';
import { getDb, getConfiguration } from '../config/config.js';
import { getLogger } from '../utils/logger.js';
import path from 'node:path';
import { BannedRecord, BannedRow, HighRiskRecord, HighRiskRow } from '../types/generator.js';
import { prep, placeholders } from './dialectUtils.js';
import { getLibraryRoot } from './findDataPath.js';

const MMDB_DIR = path.resolve(getLibraryRoot(), '_data-sources');

async function buildBannedMmdb(generateTypes: boolean, mmdbctlPath: string): Promise<void> {
    const log = getLogger().child({ service: 'BOT DETECTOR', branch: 'generator', db: 'banned' });
    const db = getDb();

    const rows = await db.prepare(
        `SELECT ip_address, country, user_agent, reason, score
         FROM banned
         WHERE ip_address IS NOT NULL`
    ).all() as BannedRow[];

    if (rows.length === 0) {
        log.info('No banned IPs — skipping banned.mmdb');
        return;
    }

    const data: BannedRecord[] = rows.map(r => ({
        range: r.ip_address,
        score: r.score,
        country: r.country,
        userAgent: r.user_agent,
        reason: r.reason,
        comment: 'Automatically generated by @riavzon/botDetector',
    }));
    await compiler<BannedRecord>({ type: 'mmdb', input: { data, dataBaseName: 'banned', outputPath: MMDB_DIR, mmdbPath: mmdbctlPath, generateTypes } });
    log.info(`banned.mmdb compiled — ${String(data.length)} entries`);

    if (getConfiguration().generator.deleteAfterBuild) {
        const compiled = rows.map(r => r.ip_address);
        const ph = placeholders(db, compiled.length);
        await prep(db, `DELETE FROM banned WHERE ip_address IN (${ph})`).run(...compiled);
        log.info(`Deleted ${(String(compiled.length))} rows from banned after build`);
    }
}


async function buildHighRiskMmdb(scoreThreshold: number, generateTypes: boolean, mmdbctlPath: string): Promise<void> {
    const log = getLogger().child({ service: 'BOT DETECTOR', branch: 'generator', db: 'highRisk' });
    const db = getDb();

    const rows = await prep(db,
        `SELECT
           ip_address, visitor_id, suspicious_activity_score,
           country, region, region_name, city, lat, lon, timezone,
           isp, org, browser, browserType, browserVersion, os,
           device_type, deviceVendor, deviceModel,
           proxy, hosting, request_count, first_seen, last_seen
         FROM visitors
         WHERE suspicious_activity_score >= ? AND ip_address IS NOT NULL`
    ).all(scoreThreshold) as HighRiskRow[];

    if (rows.length === 0) {
        log.info(`No high-risk visitors (score >= ${String(scoreThreshold)}) — skipping highRisk.mmdb`);
        return;
    }

    const data: HighRiskRecord[] = rows.map(r => ({
        range: r.ip_address,
        visitorId: r.visitor_id,
        score: r.suspicious_activity_score,
        country: r.country,
        region: r.region,
        regionName: r.region_name,
        city: r.city,
        lat: r.lat,
        lon: r.lon,
        timezone: r.timezone,
        isp: r.isp,
        org: r.org,
        browser: r.browser,
        browserType: r.browserType,
        browserVersion: r.browserVersion,
        os: r.os,
        deviceType: r.device_type,
        deviceVendor: r.deviceVendor,
        deviceModel: r.deviceModel,
        // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-conversion
        proxy: Boolean(r.proxy),
        // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-conversion
        hosting: Boolean(r.hosting),
        requestCount: r.request_count,
        firstSeen: r.first_seen ? r.first_seen.toISOString() : null,
        lastSeen: r.last_seen  ? r.last_seen.toISOString()  : null,
        comment: 'Automatically generated by @riavzon/botDetector',
    }));

    await compiler<HighRiskRecord>({ type: 'mmdb', input: { data, dataBaseName: 'highRisk', outputPath: MMDB_DIR, mmdbPath: mmdbctlPath, generateTypes } });
    log.info(`highRisk.mmdb compiled — ${String(data.length)} entries`);

    if (getConfiguration().generator.deleteAfterBuild) {
        const compiled = rows.map(r => r.ip_address);
        const ph = placeholders(db, compiled.length);
        const scorePh = placeholders(db, 1, compiled.length);
        await prep(db,
            `DELETE FROM visitors WHERE ip_address IN (${ph}) AND suspicious_activity_score >= ${scorePh}`
        ).run(...compiled, scoreThreshold);
        log.info(`Deleted ${String(compiled.length)} rows from visitors after build`);
    }
}


async function runCycle(): Promise<void> {
    const log = getLogger().child({ service: 'BOT DETECTOR', branch: 'generator' });
    const { generator } = getConfiguration();

    log.info('MMDB generation cycle started');
    try {
        await Promise.all([
            buildBannedMmdb(generator.generateTypes, generator.mmdbctlPath),
            buildHighRiskMmdb(generator.scoreThreshold, generator.generateTypes, generator.mmdbctlPath),
        ]);
        log.info('MMDB generation cycle complete');
    } catch (err) {
        log.error({ err }, 'MMDB generation cycle failed');
    }
}


export async function runGeneration(): Promise<void> {
    return runCycle();
}